name: CI Build

on:
  push:
    paths-ignore:
    - 'docs/**'
  pull_request:
    paths-ignore:
    - 'docs/**'

env:
  LC_ALL: en_US.UTF-8
  GRADLE_OPTS: -Dorg.gradle.parallel=false

jobs:
  OpenJDK8_Linux:
    name: OpenJDK8 Linux
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: GetJDK
      uses: TheMrMilchmann/install-jdk@v1
      with:
        version: '8'
        architecture: x64
    - name: Build
      shell: bash
      run: |
        ./.github/scripts/build.sh
      env:
        JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
        JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
  OpenJDK11_Linux:
    name: OpenJDK11 Linux
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      shell: bash
      run: |
        ./.github/scripts/build.sh
  OpenJDK13_Linux:
    name: OpenJDK13 Linux
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build
      shell: bash
      run: |
        ./.github/scripts/build.sh
  OpenJDK8_Local_Rebuild:
    name: OpenJDK8 Local Rebuild
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      shell: bash
      run: |
        ./.github/scripts/rebuild.sh
  OpenJDK8_Windows:
    name: OpenJDK8 Windows
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      shell: bash
      run: |
        ./.github/scripts/build.sh
  OpenJDK8_macOS:
    name: OpenJDK8 macOS
    runs-on: macos-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      shell: bash
      run: |
        ./.github/scripts/build.sh
